// src/themes/themeConfig.js
export const THEMES = {
  ocean: {
    id: 'ocean',
    name: 'Ocean Blue',
    icon: '🌊',
    fonts: 'font-sans',
    colors: {
      primary: '#0ea5e9',
      secondary: '#0284c7',
      accent: '#06b6d4',
      background: '#f0f9ff',
      text: '#0c4a6e',
      gradient: 'from-blue-500 to-cyan-500',
      button: 'bg-gradient-to-r from-blue-500 to-cyan-500 hover:shadow-lg hover:shadow-blue-500/50',
      card: 'bg-white/80 backdrop-blur-lg border border-blue-200',
      border: 'border-blue-200',
      glow: 'shadow-blue-500/30',
      hover: 'hover:bg-blue-50',
    },
  },
  sunset: {
    id: 'sunset',
    name: 'Sunset',
    icon: '🌅',
    fonts: 'font-sans',
    colors: {
      primary: '#f97316',
      secondary: '#ea580c',
      accent: '#f59e0b',
      background: '#fff7ed',
      text: '#7c2d12',
      gradient: 'from-orange-500 to-rose-500',
      button: 'bg-gradient-to-r from-orange-500 to-rose-500 hover:shadow-lg hover:shadow-orange-500/50',
      card: 'bg-white/80 backdrop-blur-lg border border-orange-200',
      border: 'border-orange-200',
      glow: 'shadow-orange-500/30',
      hover: 'hover:bg-orange-50',
    },
  },
  forest: {
    id: 'forest',
    name: 'Forest',
    icon: '🌿',
    fonts: 'font-sans',
    colors: {
      primary: '#22c55e',
      secondary: '#16a34a',
      accent: '#4ade80',
      background: '#f0fdf4',
      text: '#14532d',
      gradient: 'from-green-500 to-emerald-500',
      button: 'bg-gradient-to-r from-green-500 to-emerald-500 hover:shadow-lg hover:shadow-green-500/50',
      card: 'bg-white/80 backdrop-blur-lg border border-green-200',
      border: 'border-green-200',
      glow: 'shadow-green-500/30',
      hover: 'hover:bg-green-50',
    },
  },
  royal: {
    id: 'royal',
    name: 'Royal',
    icon: '👑',
    fonts: 'font-sans',
    colors: {
      primary: '#8b5cf6',
      secondary: '#7c3aed',
      accent: '#a78bfa',
      background: '#f5f3ff',
      text: '#4c1d95',
      gradient: 'from-purple-500 to-indigo-500',
      button: 'bg-gradient-to-r from-purple-500 to-indigo-500 hover:shadow-lg hover:shadow-purple-500/50',
      card: 'bg-white/80 backdrop-blur-lg border border-purple-200',
      border: 'border-purple-200',
      glow: 'shadow-purple-500/30',
      hover: 'hover:bg-purple-50',
    },
  },
  rose: {
    id: 'rose',
    name: 'Rose',
    icon: '🌹',
    fonts: 'font-sans',
    colors: {
      primary: '#f43f5e',
      secondary: '#e11d48',
      accent: '#fb7185',
      background: '#fff1f2',
      text: '#881337',
      gradient: 'from-rose-500 to-pink-500',
      button: 'bg-gradient-to-r from-rose-500 to-pink-500 hover:shadow-lg hover:shadow-rose-500/50',
      card: 'bg-white/80 backdrop-blur-lg border border-rose-200',
      border: 'border-rose-200',
      glow: 'shadow-rose-500/30',
      hover: 'hover:bg-rose-50',
    },
  },
  dark: {
    id: 'dark',
    name: 'Dark',
    icon: '🌙',
    fonts: 'font-sans',
    colors: {
      primary: '#fbbf24',
      secondary: '#f59e0b',
      accent: '#fcd34d',
      background: '#111827',
      text: '#f3f4f6',
      gradient: 'from-amber-400 to-yellow-500',
      button: 'bg-gradient-to-r from-amber-400 to-yellow-500 hover:shadow-lg hover:shadow-amber-500/50 text-gray-900',
      card: 'bg-gray-800/90 backdrop-blur-lg border border-gray-700',
      border: 'border-gray-700',
      glow: 'shadow-amber-500/30',
      hover: 'hover:bg-gray-700',
    },
  },
  cyber: {
    id: 'cyber',
    name: 'Cyberpunk',
    icon: '🤖',
    fonts: 'font-mono',
    colors: {
      primary: '#06b6d4',
      secondary: '#8b5cf6',
      accent: '#ec4899',
      background: '#0f172a',
      text: '#f8fafc',
      gradient: 'from-cyan-400 to-fuchsia-500',
      button: 'bg-gradient-to-r from-cyan-400 to-fuchsia-500 hover:shadow-lg hover:shadow-cyan-500/50',
      card: 'bg-slate-800/90 backdrop-blur-lg border border-cyan-500/30',
      border: 'border-cyan-500/30',
      glow: 'shadow-cyan-500/30',
      hover: 'hover:bg-slate-700',
    },
  },
  neon: {
    id: 'neon',
    name: 'Neon',
    icon: '💫',
    fonts: 'font-sans',
    colors: {
      primary: '#22d3ee',
      secondary: '#f472b6',
      accent: '#a78bfa',
      background: '#030712',
      text: '#f3f4f6',
      gradient: 'from-cyan-400 via-pink-400 to-purple-400',
      button: 'bg-gradient-to-r from-cyan-400 via-pink-400 to-purple-400 hover:shadow-lg hover:shadow-cyan-500/50',
      card: 'bg-gray-900/90 backdrop-blur-lg border border-cyan-500/20',
      border: 'border-cyan-500/20',
      glow: 'shadow-cyan-500/30',
      hover: 'hover:bg-gray-800',
    },
  },
  vintage: {
    id: 'vintage',
    name: 'Vintage',
    icon: '📜',
    fonts: 'font-serif',
    colors: {
      primary: '#b45309',
      secondary: '#92400e',
      accent: '#d97706',
      background: '#fef3c7',
      text: '#451a03',
      gradient: 'from-amber-700 to-yellow-700',
      button: 'bg-gradient-to-r from-amber-700 to-yellow-700 hover:shadow-lg hover:shadow-amber-700/50',
      card: 'bg-yellow-50/90 backdrop-blur-lg border border-amber-300',
      border: 'border-amber-300',
      glow: 'shadow-amber-700/30',
      hover: 'hover:bg-amber-100',
    },
  },
  emerald: {
    id: 'emerald',
    name: 'Emerald',
    icon: '💎',
    fonts: 'font-sans',
    colors: {
      primary: '#059669',
      secondary: '#047857',
      accent: '#34d399',
      background: '#ecfdf5',
      text: '#064e3b',
      gradient: 'from-emerald-500 to-teal-500',
      button: 'bg-gradient-to-r from-emerald-500 to-teal-500 hover:shadow-lg hover:shadow-emerald-500/50',
      card: 'bg-white/80 backdrop-blur-lg border border-emerald-200',
      border: 'border-emerald-200',
      glow: 'shadow-emerald-500/30',
      hover: 'hover:bg-emerald-50',
    },
  },
  indigo: {
    id: 'indigo',
    name: 'Indigo',
    icon: '🔮',
    fonts: 'font-sans',
    colors: {
      primary: '#4f46e5',
      secondary: '#4338ca',
      accent: '#6366f1',
      background: '#eef2ff',
      text: '#1e1b4b',
      gradient: 'from-indigo-500 to-blue-500',
      button: 'bg-gradient-to-r from-indigo-500 to-blue-500 hover:shadow-lg hover:shadow-indigo-500/50',
      card: 'bg-white/80 backdrop-blur-lg border border-indigo-200',
      border: 'border-indigo-200',
      glow: 'shadow-indigo-500/30',
      hover: 'hover:bg-indigo-50',
    },
  },
};

export const DEFAULT_THEME = 'ocean';